### PR TITLE
Added Navbar Bootstrap

### PR DESCRIPTION
**Pull request by Benhwaet**
Includes the website placeholder name, a home link, a wishlist link, a dropdown menu leading to Advanced Search, Filters, and Recommendations, followed by a Search Bar. No styling added. Only changed some button text/titles. Still needs an Advanced Search modal towards which to link.

BasicSearchNavbarScreenshot

### CODE REVIEW

**Comment by aedelfrid** [comment]
Is this just adding a CSS and JS file? You may better be able to integrate by pulling branch 'first-commit' then committing and then pushing in that branch. You could also potentially branch from 'first-commits' so you can do your own thing but from a more up to date branch.

**Comment by hineeraja** [comment]
> Is this just adding a CSS and JS file? You may better be able to integrate by pulling branch 'first-commit' then committing and then pushing in that branch. You could also potentially branch from 'first-commits' so you can do your own thing but from a more up to date branch.

Oh yea, I think that helps to track updates and changes

**Comment by Benhwaet** [comment]
That makes a lot more sense! I just didn't think of it. I'll do it before tonight if I have a few minutes. I liked the format of that search-bar framework.

**Comment by aedelfrid** [comment]
no sweat! it is looking good! we can chat about it tonight but if you feel like it/ get the time, what you can do is close this pull request then in your CLI do “git fetch first-commits” then “git switch first-commits” then you should be able to commit and push.

**Comment by aedelfrid** [comment]
actually I think we'll have to chat about logistics tonight before we move too far forward. Tonight's agenda I figure we'll go; logistics, present APIs, concerns maybe? then work on things? Will post this in slack too for maximum visibility.

**Pull request closed without merging**
